### ISSUE TITLE
Support YAML format for VMware Event Router Configuration

### ISSUE THREAD

**Issue by embano1** [vmware-samples/vcenter-event-broker-appliance#179]
**Is your feature request related to a problem? Please describe.**
To support templating of the VMware Event Router configuration file, e.g. via Helm, YAML would be the preferred (in case of Helm only) option.

**Describe the solution you'd like**
Instead of JSON use YAML as configuration syntax for the `-config` of the Event Router.

**Describe alternatives you've considered**
JSON templating solutions, but Helm and others (YTT) have bigger communities.

**Comment by embano1** [comment]
Here's a first attempt to migrate the current JSON-based configuration format in use to YAML with some additional fields to support versioning, naming of resources, extensibility (`[]Provider|Processor`) and cleanup for better readability/consistency.

```yaml
apiVersion: event-router.vmware.com/v1alpha1
kind: RouterConfiguration
metadata:
  labels:
    testkey: testvalue
eventProvider:
  type: vcenter
  name: vcenter01-prod
  vcenter:
    address: https://10.0.0.1:443/sdk
    auth:
      type: basic
      basicAuth:
        username: admin
        password: VMware1!
eventProcessor:
  type: aws_event_bridge
  name: awseb-us-west
  awsEventBridge:
    region: us-west-1
    eventBus: ABCDEFG123454/awseb/default
    ruleArn: ABCDEFG123454/awseb/rule/1233456
    auth:
      type: aws_access_key
      awsAccessKeyAuth:
        accessKey: ABCDEFGH12345
        secretKey: 263dnbed263enbd
metricsProvider:
  type: internal
  name: default
  internal:
    bindAddress: 0.0.0.0:8081
    auth:
      type: basic
      basicAuth:
        username: root
        password: nimda
```

@lamw would this work with regards to templatizing the config file (e.g. helm) now?
