### ISSUE TITLE
Track CVE-2020–15257

### ISSUE THREAD

**Issue by embano1** [vmware-samples/vcenter-event-broker-appliance#263]
**Describe the bug**
Security issue:
https://medium.com/nttlabs/dont-use-host-network-namespace-f548aeeef575

Explore if this works for envoy

```yaml
hostNetwork: true
containers:
- name: foo
  securityContext:
    runAsUser: 12345
    allowPrivilegeEscalation: false 
```
