### ISSUE TITLE
Knative Broker not found with Knative 0.16.0

### ISSUE THREAD

**Issue by sp-schoen** [vmware-samples/vcenter-event-broker-appliance#301]
**Describe the bug**
When using an older Version of Knative (0.16.0 in my case), addressing the sink (Broker) via a K8s reference doesn't work, because the Function used to get the URL for the Ressource is for "v1"-Ressources. But in older versions of Knative, the Broker-Ressource for example has the Version v1beta1. It seems like there is also a function in the Knative libraries to search for these Ressources.

**To Reproduce**
Run the Event-Router in K8s with an older Knative-Version (0.16.0 for example) and create a Broker with the Version v1beta1. Then configure this Broker via a K8s reference as event-sink. The event router will fail at startup while trying to localise the K8s ressource.

**Expected behavior**
Also v1beta1 Knative ressources are found by the event router.

**Version (please complete the following information):**
 - VEBA Form Factor: K8s (with OpenShift 4 and Knative (0.16.0))
 - VEBA Version: v0.5.0

**Additional context**
Knative is installed via an OpenShift-Operator. Therefore it is now not possible for us to upgrade to a later Knative version.
For now we use the url of the Broker directly in the event router config, but that is very ugly.

**Comment by embano1** [comment]
Assuming you're talking about this line where the router errors out in your case?

```go
	uri, err := uriResolver.URIFromDestinationV1(ctx, *cfg.Destination, &source)
	if err != nil {
		return nil, errors.Wrap(err, "get URI from destination")
	}
```

And you would like us to support this method then, right?

```go
// URIFromDestination resolves a v1beta1.Destination into a URI string.
func (r *URIResolver) URIFromDestination(ctx context.Context, dest duckv1beta1.Destination, parent interface{}) (string, error) {
```

**Comment by vaikas** [comment]
Do you have an example configuration that fails? As long as you use v1beta1 in the sink that should work, so if there's a way to get a minimal repro, I'd love to see it. Or maybe I'm missing something here :)

**Comment by sp-schoen** [comment]
@vaikas My Broker config:
```
apiVersion: eventing.knative.dev/v1beta1
kind: Broker
metadata:
  annotations:
    eventing.knative.dev/broker.class: MTChannelBasedBroker
  creationTimestamp: "2021-02-04T14:13:48Z"
  finalizers:
  - brokers.eventing.knative.dev
  generation: 1
  name: default
  namespace: xxxx
spec:
  config:
    apiVersion: v1
    kind: ConfigMap
    name: config-br-default-channel
    namespace: knative-eventing
```

Router-Config:
```
eventProcessor:
  type: knative
  knative:
    destination:
      ref:
        apiVersion: eventing.knative.dev/v1 # also tested with v1beta1
        kind: Broker
        name: default
        namespace: xxxx
    encoding: binary
    insecureSSL: true
```

Log:
`[MAIN]	router/main.go:146	could not create Knative processor: get URI from destination: brokers.eventing.knative.dev "Lister" not found`

**Comment by sp-schoen** [comment]
@embano1 
Yes, that looks correct.

**Comment by embano1** [comment]
I will also discuss this with @vaikas but quick question: did you set up RBAC for the router so it can ListWatch the resources?

```bash
kubectl create clusterrolebinding veba-addressable-resolver --clusterrole=addressable-resolver --serviceaccount=vmware:vmware-event-router
```

This is described here: https://github.com/vmware-samples/vcenter-event-broker-appliance/tree/development/vmware-event-router#create-knative-clusterrolebinding-skip-if-not-using-knative

**Comment by sp-schoen** [comment]
Sorry, I overlooked this in the instructions. I will try it.

**Comment by sp-schoen** [comment]
I added the cluster-rolebinding, but it didn't change anything. Same error-message as before.

**Comment by embano1** [comment]
Just to doublecheck, the router is also using that specified service account right?

**Comment by sp-schoen** [comment]
`serviceAccountName: vmware-event-router` is set in my DeploymentConfig.

**Comment by embano1** [comment]
I tried to reproduce the issue locally with Knative v0.16 but don't see your described behavior. Here's what I did (using `kind` cluster):

Create an event router config (secret) as per the documentation, using a default (in-memory) broker and the v1beta1 APIs:

```yaml
apiVersion: event-router.vmware.com/v1alpha1
kind: RouterConfig
metadata:
  name: router-config-knative
  labels:
    key: value
eventProvider:
  type: vcenter
  name: veba-demo-vc-01
  vcenter:
    address: https://vcenter.ip
    insecureSSL: true
    checkpoint: false
    auth:
      type: basic_auth
      basicAuth:
        username: administrator@vsphere.local
        password: password
eventProcessor:
  name: veba-demo-knative
  type: knative
  knative:
    encoding: structured
    insecureSSL: false
    destination:
      ref:
        apiVersion: eventing.knative.dev/v1beta1
        kind: Broker
        name: default
        namespace: default
metricsProvider:
  type: default
  name: veba-demo-metrics
  default:
    bindAddress: "0.0.0.0:8082"
```

Create a cluster role binding for the router, service account (see below) and namespace (I use `vmware` as namespace):

```bash
kubectl create clusterrolebinding veba-addressable-resolver --clusterrole=addressable-resolver --serviceaccount=vmware:vmware-event-router
```

Deploy the router with the K8s deployment manifest in `deploy/` (will also create service account).

Router comes up, is able to resolve the broker and starts streaming events:

```bash
vmware vmware-event-router-b88f9b77f-26dtj vmware-event-router
vmware vmware-event-router-b88f9b77f-26dtj vmware-event-router  _    ____  ___                            ______                 __     ____              __
vmware vmware-event-router-b88f9b77f-26dtj vmware-event-router | |  / /  |/  /      ______ _________     / ____/   _____  ____  / /_   / __ \____  __  __/ /____  _____
vmware vmware-event-router-b88f9b77f-26dtj vmware-event-router | | / / /|_/ / | /| / / __  / ___/ _ \   / __/ | | / / _ \/ __ \/ __/  / /_/ / __ \/ / / / __/ _ \/ ___/
vmware vmware-event-router-b88f9b77f-26dtj vmware-event-router | |/ / /  / /| |/ |/ / /_/ / /  /  __/  / /___ | |/ /  __/ / / / /_   / _, _/ /_/ / /_/ / /_/  __/ /
vmware vmware-event-router-b88f9b77f-26dtj vmware-event-router |___/_/  /_/ |__/|__/\__,_/_/   \___/  /_____/ |___/\___/_/ /_/\__/  /_/ |_|\____/\__,_/\__/\___/_/
vmware vmware-event-router-b88f9b77f-26dtj vmware-event-router
vmware vmware-event-router-b88f9b77f-26dtj vmware-event-router 2021-02-16T12:39:57.488Z INFO    [MAIN]  router/main.go:111      connecting to vCenter   {"address": "https://10.161.153.226"}
vmware vmware-event-router-b88f9b77f-26dtj vmware-event-router 2021-02-16T12:39:57.488Z INFO    [KNATIVE]       injection/injection.go:61       Starting informers...
vmware vmware-event-router-b88f9b77f-26dtj vmware-event-router 2021-02-16T12:39:57.604Z INFO    [MAIN]  router/main.go:149      created Knative processor       {"sink": "http://broker-ingress.knative-eventing.svc.cluster.local/default/default"}
vmware vmware-event-router-b88f9b77f-26dtj vmware-event-router 2021-02-16T12:39:57.604Z WARN    [METRICS]       metrics/server.go:59    no credentials found, disabling authentication for metrics server
vmware vmware-event-router-b88f9b77f-26dtj vmware-event-router 2021-02-16T12:39:57.605Z INFO    [METRICS]       metrics/server.go:131   starting metrics server {"address": "http://0.0.0.0:8082/stats"}
vmware vmware-event-router-b88f9b77f-26dtj vmware-event-router 2021-02-16T12:39:57.849Z INFO    [VCENTER]       vcenter/vcenter.go:174  checkpointing disabled, setting begin of event stream   {"beginTimestamp": "2021-02-16 12:39:57.721495 +0000 UTC"}
vmware vmware-event-router-b88f9b77f-26dtj vmware-event-router 2021-02-16T12:40:39.399Z INFO    [VCENTER]       vcenter/vcenter.go:304  invoking processor      {"eventID": "9b809007-7aad-4806-a009-b884b1a5bdb6"}
vmware vmware-event-router-b88f9b77f-26dtj vmware-event-router 2021-02-16T12:40:39.400Z INFO    [KNATIVE]       knative/knative.go:180  sending event   {"eventID": "9b809007-7aad-4806-a009-b884b1a5bdb6", "subject": "TaskEvent"}
```

Note that even in Knative v0.16 the eventing CRD serves `v1` for the broker (storage is `v1beta1` though). That's why the v1Resolver works as well.

```bash
k get crds brokers.eventing.knative.dev -o json | jq -r '.spec.versions[]|"version: "+.name,"storage: "+(.storage|tostring)'
version: v1alpha1
storage: false
version: v1beta1
storage: true
version: v1
storage: false
```
