### ISSUE TITLE
OpenFaaS function invocation count is always 0

### ISSUE THREAD

**Issue by rguske** [vmware-samples/vcenter-event-broker-appliance#306]
**Describe the bug**
The function invocation count, which can be displayed by using the OpenFaaS portal as well as by using `faas-cli list` is always 0.

**To Reproduce**
1. deploy a fresh instance of VEBA - [download](https://flings.vmware.com/vmware-event-broker-appliance)
2. deploy one of the example functions - e.g. [restpost function](https://github.com/vmware-samples/vcenter-event-broker-appliance/tree/development/examples/python/invoke-rest-api)
3. invoke the function via the specified vCenter event like e.g. `VmPoweredOn`
4. check the invocation count via the OpenFaaS portal or by using `faas-cli list`

**Expected behavior**
The invocation count should increase every time the function(s) gets invoked.

**Screenshots**
The following log output shows the successful invocation of the function `restpost-fn.openfaas-fn`.

```
2021-02-05T16:53:22.139Z        INFO    [OPENFAAS]      openfaas/openfaas.go:242        successfully invoked function   {"function": "restpost-fn.openfaas-fn", "topic": "VmPoweredOffEvent", "retries": 0}
2021-02-05T16:53:22.139Z        INFO    [OPENFAAS]      openfaas/openfaas.go:197        finished processing of event    {"eventID": "797abbe8-abcd-411d-a100-9f2fdf3743c9", "topic": "VmPoweredOffEvent"}
2021-02-05T16:53:34.365Z        INFO    [VCENTER]       vcenter/vcenter.go:304  invoking processor      {"eventID": "9f702f6c-707a-448b-9bfb-277515b473bc"}
```

The invocation count stays 0.

```
faas-cli list --tls-no-verify
Function                        Invocations     Replicas
powercli-tag                    0               1    
restpost-fn                     0               1
```

**Version (please complete the following information):**
 - VEBA Form Factor: Appliance
 - VEBA Version: 
```
root@veba-of [ /etc ]# cat veba-release 
Version: v0.5.0
Commit: dd37b48
Processor: OpenFaaS
```

Image versions of the OpenFaaS components:
`openfaas/gateway:0.18.17`
`prom/prometheus:v2.11.0`
`openfaas/basic-auth-plugin:0.18.17`

**Additionally:**
Everything works as expected when deploying "VEBA" on Kubernetes. The OpenFaaS component versions differs from the listed ones (Appliance) above.

Versions:
`openfaas/gateway:0.20.2`
`prom/prometheus:v2.11.0`
`openfaas/basic-auth-plugin:0.20.1`

**Comment by lamw** [comment]
Looks like the `prometheus-rbac.yml" is missing `openfaas` namespace and hence the Role is deployed to defualt namespae versus where it should be. 

```
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: openfaas-prometheus
  namespace: "openfaas" <-----THIS WAS MISSING
  labels:
    app: openfaas
    component: prometheus
rules:
- apiGroups: [""]
  resources:
    - services
    - endpoints
    - pods
  verbs: ["get", "list", "watch"]
```

I've got a fix for this, will test and then submit PR
