### ISSUE TITLE
Ingress configuration always contains VEBA UI endpoints

### ISSUE THREAD

**Issue by lamw** [vmware-samples/vcenter-event-broker-appliance#354]
**Describe the bug**
It looks like [setup-09-ingress.sh](https://github.com/vmware-samples/vcenter-event-broker-appliance/blob/development/files/setup-09-ingress.sh) does not verify whether the deployment will setup VEBA UI and hence the ingress configuration always contains the VEBA UI endpoints. This is problematic since the behavior for the customer is that VEBA UI configurations were not applied and hence, the system should not configure the VEBA UI endpoints within the ingress controller as this will cause it to have invalid state

**To Reproduce**
1) Deploy OVA using Embedded Knative option BUT do NOT fill in username/password for registering the VEBA UI
2) Endpoints such as /status, /stats and /events fail due to invalid ingress configuration

**Expected behavior**
Ingress configuration does not contain VEBA UI endpoints when user 

**Screenshots**
```
 conditions:
  - errors:
    - message: 'Spec.Routes unresolved service reference: service "vmware-system/veba-ui"
        not found'
      reason: ServiceUnresolvedReference
      status:
```

**Version (please complete the following information):**
 - VEBA Form Factor: Appliance
 - VEBA Version: v0.6.0

**Additional context**
Slack Discussion: https://vmwarecode.slack.com/archives/CQLT9B5AA/p1619001864106000
