### ISSUE TITLE
Update Knative and related component versions to latest v0.2x version

### ISSUE THREAD

**Issue by lamw** [vmware-samples/vcenter-event-broker-appliance#509]
**Is your feature request related to a problem? Please describe.**
As part of keeping VEBA BOM up to date, we should update Knative and the respective components such as Knative Contour, RabbitMQ Operator, etc. to latest v0.2x

**Comment by embano1** [comment]
@lamw heads-up when deploying newer `RabbitMQ` version: you need to set this annotation in the `RabbitMQCluster` configuration to allow for a Rabbit cluster to be deployed in a different namespace (`vmware-system`) than the Knative `broker` (`vmware-functions`):

```yaml
metadata:
  annotations:
    rabbitmq.com/topology-allowed-namespaces: '*'
```
