### ISSUE TITLE
[BUG] Regression in v0.7.2-pre RabbitMQ image not pre-pulled

### ISSUE THREAD

**Issue by embano1** [vmware-samples/vcenter-event-broker-appliance#795]
PR #683 dropped the `rabbitmq` image to be pulled during VEBA setup: https://github.com/vmware-samples/vcenter-event-broker-appliance/commit/a5f5c2ba3d6db55c2d2cd296e5ed5a2204b4bd07#diff-89c3a63823865a71b59d1454d3197b17b38ef18a9a93f735a017b6f300584e8bL149-R162

BOM line missing:

```
{
                "name": "rabbitmq",
                "version": "3.8.9-management"
}
```

`version` has to match whatever the RabbitMQ operator uses by default (changes with release). Proposal: specify the required image in the `RabbitMQCluster` spec:

```yaml
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: veba-rabbit
  namespace: vmware-system
  annotations:
    rabbitmq.com/topology-allowed-namespaces: "vmware-functions"
spec:
  image: <insert_here>
  resources:
    requests:
      memory: 200Mi
      cpu: 100m
  replicas: 1
---
apiVersion: eventing.knative.dev/v1
kind: Broker
metadata:
  name: default
  namespace: vmware-functions
  annotations:
    eventing.knative.dev/broker.class: RabbitMQBroker
spec:
  config:
    apiVersion: rabbitmq.com/v1beta1
    kind: RabbitmqCluster
    name: veba-rabbit
    namespace: vmware-system
  delivery:
    retry: 2
    backoffPolicy: linear
```

https://github.com/vmware-samples/vcenter-event-broker-appliance/blob/development/files/configs/knative/rabbit.yaml
