### ISSUE TITLE
[Enhancement] vmware-event-router : enable the AWS EventBridge `Processor` to use an assumed IAM Role

### ISSUE THREAD

**Issue by AdrianBegg** [vmware-samples/vcenter-event-broker-appliance#823]
**Is your feature request related to a problem? Please describe.**
In the current implementation of the AWS EventBridge `Processor` within the vmware-event-router a static AWS Access Key/Secret Access Key is required to be hardcoded in the configuration file for authentication with AWS. The proposed enhancement is to add a switch for the AWS EventBridge processor type which would enable AWS SDK Session used in the project to be established using an assumed IAM Role (if the container is running in Amazon EKS). The purpose of this would be to improve the security of the project when deployed on AWS to not use hardcoded Access Key/Secret Access as per AWS best-practices.

**Describe the solution you'd like**
It is proposed to adjust the config to support a new `auth` type for the `eventProcessor` **aws_event_bridge** of type `aws_iam_role`. When this is set (instead of the type `aws_access_key`) the AWS SDK Session will use the secrets for the executing user (e.g. secrets with temporary access credentials mounted to the EKS Container with the container role credentials).

The following sample configuration outlines the adjusted usage for the configuration file:
```
eventProcessor:
  type: aws_event_bridge
  name: veba-aws-eventbridge
  awsEventBridge:
    eventBus: arn:aws:events:us-east-2:XXXXXXXXXXX:event-bus/veba-event-router
    region: us-east-2
    ruleARN: arn:aws:events:us-east-2:XXXXXXXXXX:rule/veba-event-router/veba-event-router-filters
    auth:
      type: aws_iam_role
```

The `func NewEventBridgeProcessor` in `internal/processor/aws/aws_event_bridge.go` would be adjusted such that the AWS SDK Session would be established without the credentials being passed such that the default AWS SDK connection behavior would be triggered.

**Describe alternatives you've considered**
An alternative to rotate the secrets and updating the Secrets via API; using AssumeRole temporary security credentials provides the ability for short-lived credentials but also enables specific Role Permissions to be granted/revoked for individual vmware-event-router pods without managing credentials.

**Additional context**
